version: smartide/v0.2
orchestrator:
  type: allinone
  version: 3
workspace:
  dev-container:
    service-name: boathouse-dev
    ports: # 申明端口
      tools-webide-vscode: 6800
      tools-ssh: 6822
      tools-phpmyadmin: 8090
      tools-nacos: 8848
      apps-ruoyi-ui: 8000
      apps-ruoyi-admin: 8080
    
    ide-type: vscode
    volumes: 
      git-config: true
      ssh-key: true
    command:
      - cd /home/project
      - code --install-extension vscjava.vscode-java-pack
      - code --install-extension ms-azuretools.vscode-docker

  kube-deploy-files: "k8s-deployment-vmlc.yaml" 
  docker-compose-file: "docker-compose-vmlc.yaml"
