version: smartide/v0.2
orchestrator:
  type: docker-compose
  version: 3
workspace:
  dev-container:
    service-name: product-service-dev
    webide-port: 6800
  services:

    product-service-dev:
      image: registry.cn-hangzhou.aliyuncs.com/smartide/smartide-java:latest
      restart: always
      environment:
        POSTGRES_HOST_AUTH_METHOD: trust
        ROOT_PASSWORD: root123
      volumes:
        - .:/home/project
      ports:
        - 3000
      networks:
        - smartide-network

    product-service-db:
      image: mysql:5.6
      command: 
        - --default-authentication-plugin=mysql_native_password
      restart: always
      volumes:
        - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      ports:
        - 3306
      environment:
        MYSQL_ROOT_PASSWORD: P2ssw0rd
      networks:
        - smartide-network
  networks:
    smartide-network:
      external: true
